export const ENVIRONMENT_QUERIES_PREFIX = "ENVIRONMENT";
export const GET_ENVIRONMENTS = "GET_ENVIRONMENTS";
export const GET_PAGINATED_ENVIRONMENTS = "GET_PAGINATED_ENVIRONMENTS";
export const CREATE_ENVIRONMENT = "CREATE_ENVIRONMENT";
export const UPDATE_ENVIRONMENT = "UPDATE_ENVIRONMENT";
export const DELETE_ENVIRONMENT = "DELETE_ENVIRONMENT";
