export const PROJECT_QUERIES_PREFIX = "PROJECT_QUERIES_PREFIX";

//? projects constants
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PAGINATED_PROJECTS = "GET_PAGINATED_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const EXPORT_PROJECTS = "EXPORT_PROJECTS";
