import { Injectable } from '@nestjs/common';

export interface DocumentTemplateSnapshot {
  id: string;
  name: string;
  title: string;
  footer: string;
  showStatistics: boolean;
  showExecutions: boolean;
  showPreconditions: boolean;
  showSteps: boolean;
  showApprovals: boolean;
  showContext: boolean;
  failedOnly: boolean;
}

@Injectable()
export class DocumentTemplateService {
  getActiveTemplate(templateCode?: string): DocumentTemplateSnapshot {
    if (templateCode === 'compact') {
      return {
        id: 'compact',
        name: 'Compact Template',
        title: 'Compact Document',
        footer: 'Generated by TestLab',
        showStatistics: true,
        showExecutions: false,
        showPreconditions: false,
        showSteps: true,
        showApprovals: false,
        showContext: true,
        failedOnly: false,
      };
    }

    if (templateCode === 'failure-focus') {
      return {
        id: 'failure-focus',
        name: 'Failure Focus Template',
        title: 'Failure Investigation Report',
        footer: 'Generated by TestLab',
        showStatistics: true,
        showExecutions: true,
        showPreconditions: true,
        showSteps: true,
        showApprovals: true,
        showContext: true,
        failedOnly: true,
      };
    }

    return {
      id: 'default',
      name: 'Default Template',
      title: 'Project Document',
      footer: 'Generated by TestLab',
      showStatistics: true,
      showExecutions: true,
      showPreconditions: true,
      showSteps: true,
      showApprovals: true,
      showContext: true,
      failedOnly: false,
    };
  }
}