import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '_prisma/client';
import { PrismaService } from '../../database/prisma.service';
import type {
  CahierSelectionSuiteDto,
  FsdSelectionEpicDto,
} from '../dto/document-selection.dto';
import type {
  CahierDocumentModel,
  DocumentTemplateSnapshot,
  FsdDocumentModel,
} from '../interfaces/document-model.interface';

type FsdDataOverrides = {
  metadata?: Partial<FsdDocumentModel['metadata']>;
  introduction?: Partial<FsdDocumentModel['introduction']>;
  overallDescription?: Partial<FsdDocumentModel['overallDescription']>;
  projectOverview?: string;
  methodology?: string;
  approvals?: FsdDocumentModel['approvals'];
  referenceDocuments?: FsdDocumentModel['referenceDocuments'];
  glossary?: FsdDocumentModel['glossary'];
  revisions?: FsdDocumentModel['revisions'];
  editValues?: Record<string, string>;
  richEditValues?: Record<string, string>;
  sectionBackgroundValues?: Record<string, string>;
  pageStyle?: {
    backgroundColor?: string;
  };
  excludedImageIds?: string[];
};

type FsdDataOptions = {
  selectedEpicIds?: string[];
  selectedFeatureIds?: string[];
  selectedUserStoryIds?: string[];
  overrides?: FsdDataOverrides;
};

type PersistFsdStepTwoInput = {
  approvals?: Array<{
    name?: string;
    role?: string;
    date?: string;
  }>;
  referenceDocuments?: Array<{
    name?: string;
    type?: string;
    attachment?: string;
  }>;
  glossary?: Array<{
    term?: string;
    comment?: string;
  }>;
  revisions?: Array<{
    date?: string;
    version?: string;
    status?: string;
    authors?: string[];
    author?: string;
  }>;
};

function normalizeAuthors(authors?: string[], author?: string): string[] {
  const normalized = (authors || [])
    .map((item) => (item || '').trim())
    .filter((item) => item.length > 0);

  if (normalized.length > 0) {
    return normalized;
  }

  if (author?.trim()) {
    return [author.trim()];
  }

  return [];
}

type CahierDataOverrides = {
  metadata?: Partial<CahierDocumentModel['metadata']>;
  context?: Partial<CahierDocumentModel['context']>;
  project?: Partial<CahierDocumentModel['project']>;
  approvals?: CahierDocumentModel['approvals'];
  editValues?: Record<string, string>;
  richEditValues?: Record<string, string>;
  sectionBackgroundValues?: Record<string, string>;
  pageStyle?: {
    backgroundColor?: string;
  };
};

type CahierDataOptions = {
  selectedSuiteIds?: string[];
  selectedTestCaseIds?: string[];
  overrides?: CahierDataOverrides;
};

function formatDate(date: Date): string {
  return date.toLocaleDateString('fr-FR');
}

@Injectable()
export class DocumentDataService {
  constructor(private readonly prisma: PrismaService) {}

  private readonly defaultTemplate: DocumentTemplateSnapshot = {
    id: 'default',
    name: 'Default Template',
    title: 'Project Quality Report',
    footer: 'Generated by TestLab Documents Module',
    showStatistics: true,
    showExecutions: true,
    showPreconditions: true,
    showSteps: true,
    showApprovals: true,
    showContext: true,
    failedOnly: false,
  };

  getTemplates(): DocumentTemplateSnapshot[] {
    return [
      this.defaultTemplate,
      {
        ...this.defaultTemplate,
        id: 'compact',
        name: 'Compact Template',
        title: 'Compact Test Summary',
        showExecutions: false,
        showPreconditions: false,
        showApprovals: false,
      },
    ];
  }

  async persistFsdStepTwoData(
    projectId: string,
    payload: PersistFsdStepTwoInput,
  ): Promise<void> {
    await this.ensureProjectExists(projectId);

    const approvals = (payload.approvals || [])
      .filter(
        (approval) =>
          approval.name?.trim() &&
          approval.role?.trim() &&
          approval.date?.trim(),
      )
      .map((approval) => {
        const parsedDate = approval.date ? new Date(approval.date) : null;
        return {
          projectId,
          approverName: approval.name!.trim(),
          approverRole: approval.role!.trim(),
          approvalDate:
            parsedDate && !Number.isNaN(parsedDate.getTime())
              ? parsedDate
              : new Date(),
        };
      });

    const referenceDocuments = (payload.referenceDocuments || [])
      .filter(
        (item) =>
          item.name?.trim() && item.type?.trim() && item.attachment?.trim(),
      )
      .map((item, index) => ({
        projectId,
        name: item.name!.trim(),
        type: item.type!.trim(),
        attachment: item.attachment!.trim(),
        order: index,
      }));

    const glossaryEntries = (payload.glossary || [])
      .filter((item) => item.term?.trim() && item.comment?.trim())
      .map((item, index) => ({
        projectId,
        term: item.term!.trim(),
        comment: item.comment!.trim(),
        order: index,
      }));

    const revisions = (payload.revisions || [])
      .filter(
        (item) =>
          item.date?.trim() &&
          item.version?.trim() &&
          item.status?.trim() &&
          normalizeAuthors(item.authors, item.author).length > 0,
      )
      .map((item, index) => {
        const parsedDate = item.date ? new Date(item.date) : null;
        const normalizedAuthors = normalizeAuthors(item.authors, item.author);
        return {
          projectId,
          date:
            parsedDate && !Number.isNaN(parsedDate.getTime())
              ? parsedDate
              : new Date(),
          version: item.version!.trim(),
          status: item.status!.trim(),
          author: normalizedAuthors.join('; '),
          order: index,
        };
      });

    await this.prisma.$transaction(async (tx) => {
      if (payload.approvals !== undefined) {
        await tx.documentApproval.deleteMany({ where: { projectId } });
        if (approvals.length > 0) {
          await tx.documentApproval.createMany({ data: approvals });
        }
      }

      if (payload.referenceDocuments !== undefined) {
        await tx.fsdReferenceDocument.deleteMany({ where: { projectId } });
        if (referenceDocuments.length > 0) {
          await tx.fsdReferenceDocument.createMany({ data: referenceDocuments });
        }
      }

      if (payload.glossary !== undefined) {
        await tx.fsdGlossary.deleteMany({ where: { projectId } });
        if (glossaryEntries.length > 0) {
          await tx.fsdGlossary.createMany({ data: glossaryEntries });
        }
      }

      if (payload.revisions !== undefined) {
        await tx.fsdRevision.deleteMany({ where: { projectId } });
        if (revisions.length > 0) {
          await tx.fsdRevision.createMany({ data: revisions });
        }
      }
    });
  }

  async getSelectableEpicsForFsd(projectId: string): Promise<FsdSelectionEpicDto[]> {
    await this.ensureProjectExists(projectId);

    const epics = await this.prisma.epic.findMany({
      where: { projectId },
      orderBy: [{ creationDate: 'asc' }, { name: 'asc' }],
      include: {
        _count: {
          select: { features: true },
        },
        features: {
          orderBy: [{ creationDate: 'asc' }, { name: 'asc' }],
          select: {
            id: true,
            name: true,
            _count: {
              select: { userStories: true },
            },
            userStories: {
              orderBy: [{ creationDate: 'asc' }, { name: 'asc' }],
              select: {
                id: true,
                name: true,
                description: true,
              },
            },
          },
        },
      },
    });

    return epics.map((epic) => ({
      id: epic.id,
      name: epic.name,
      featureCount: epic._count.features,
      userStoryCount: epic.features.reduce(
        (total, feature) => total + feature._count.userStories,
        0,
      ),
      features: epic.features.map((feature) => ({
        id: feature.id,
        name: feature.name,
        userStoryCount: feature._count.userStories,
        userStories: feature.userStories.map((story) => ({
          id: story.id,
          name: story.description?.trim() ? story.description : story.name,
        })),
      })),
    }));
  }

  async getSelectableSuitesForCahier(
    projectId: string,
  ): Promise<CahierSelectionSuiteDto[]> {
    await this.ensureProjectExists(projectId);

    const suites = await this.prisma.testSuite.findMany({
      where: { projectId },
      orderBy: [{ order: 'asc' }, { name: 'asc' }],
      include: {
        testCases: {
          orderBy: [{ name: 'asc' }],
          select: {
            id: true,
            name: true,
          },
        },
        _count: {
          select: {
            testCases: true,
            children: true,
          },
        },
      },
    });

    return suites.map((suite) => ({
      id: suite.id,
      name: suite.name,
      order: suite.order,
      parentId: suite.parentId,
      testCaseCount: suite._count.testCases,
      childSuiteCount: suite._count.children,
      testCases: suite.testCases.map((testCase) => ({
        id: testCase.id,
        name: testCase.name,
      })),
    }));
  }

  async getCahierData(
    projectId: string,
    options?: CahierDataOptions,
  ): Promise<CahierDocumentModel> {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      include: {
        approvals: {
          orderBy: [{ createdAt: 'asc' }],
        },
        testSuites: {
          orderBy: [{ order: 'asc' }, { name: 'asc' }],
          include: {
            testCases: {
              include: {
                preconditions: { orderBy: [{ order: 'asc' }] },
                steps: { orderBy: [{ order: 'asc' }] },
              },
              orderBy: [{ name: 'asc' }],
            },
          },
        },
      },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const suitesByParent = new Map<string | null, typeof project.testSuites>();

    for (const suite of project.testSuites) {
      const key = suite.parentId ?? null;
      const existing = suitesByParent.get(key) ?? [];
      existing.push(suite);
      suitesByParent.set(key, existing);
    }

    const buildSuite = (suite: (typeof project.testSuites)[number]): CahierDocumentModel['suites'][number] => {
      const children = (suitesByParent.get(suite.id) ?? [])
        .sort((a, b) => {
          const ao = a.order ?? Number.MAX_SAFE_INTEGER;
          const bo = b.order ?? Number.MAX_SAFE_INTEGER;
          if (ao !== bo) return ao - bo;
          return a.name.localeCompare(b.name);
        })
        .map(buildSuite);

      return {
        id: suite.id,
        name: suite.name,
        order: suite.order,
        children,
        testCases: suite.testCases.map((testCase) => ({
          id: testCase.id,
          code: `TC-${testCase.id.slice(0, 8)}`,
          name: testCase.name,
          summary: testCase.summary || 'No summary provided.',
          preconditions: testCase.preconditions.map((precondition, index) => ({
            content: precondition.content,
            order: precondition.order ?? index + 1,
          })),
          steps: testCase.steps.map((step, index) => ({
            order: step.order ?? index + 1,
            action: step.action,
            expectedResult: step.expectedResult,
          })),
        })),
      };
    };

    const rootSuites = (suitesByParent.get(null) ?? [])
      .sort((a, b) => {
        const ao = a.order ?? Number.MAX_SAFE_INTEGER;
        const bo = b.order ?? Number.MAX_SAFE_INTEGER;
        if (ao !== bo) return ao - bo;
        return a.name.localeCompare(b.name);
      })
      .map(buildSuite);

    const selectedSuiteIds = new Set(options?.selectedSuiteIds ?? []);
    const selectedTestCaseIds = new Set(options?.selectedTestCaseIds ?? []);
    const shouldFilterTestCases = selectedTestCaseIds.size > 0;

    const suitesWithSelectedTestCases = shouldFilterTestCases
      ? this.filterSuitesBySelectedTestCases(rootSuites, selectedTestCaseIds)
      : rootSuites;

    const filteredSuites =
      selectedSuiteIds.size > 0
        ? this.filterSelectedSuites(suitesWithSelectedTestCases, selectedSuiteIds)
        : suitesWithSelectedTestCases;

    const result: CahierDocumentModel = {
      metadata: {
        title: `Cahier de Recette - ${project.name}`,
        clientName: project.clientName || project.name,
        author: this.resolveAuthor(),
        version: '1.0',
        date: formatDate(new Date()),
      },
      editValues: {},
      richEditValues: {},
      sectionBackgroundValues: {},
      pageStyle: {
        backgroundColor: '#ffffff',
      },
      context: {
        description:
          project.description ||
          `Cahier de recette generated from project ${project.name}.`,
        objective: `Validate test scenarios and expected outcomes for ${project.name}.`,
      },
      project: {
        id: this.projectNumericId(project.id),
        name: project.name,
        owner: project.projectOwner || 'N/A',
        openDefects: project.openDefects,
      },
      suites: filteredSuites,
      approvals: project.approvals.map((approval) => ({
        // Keep legacy keys and add new aliases for DOCX placeholders.
        name: approval.approverName,
        role: approval.approverRole,
        date: formatDate(approval.approvalDate),
        approverName: approval.approverName,
        approverRole: approval.approverRole,
        approvalDate: formatDate(approval.approvalDate),
      })),
      template: this.defaultTemplate,
    };

    if (options?.overrides?.metadata) {
      result.metadata = {
        ...result.metadata,
        ...this.omitUndefined(options.overrides.metadata),
      };
    }

    if (options?.overrides?.context) {
      result.context = {
        ...result.context,
        ...this.omitUndefined(options.overrides.context),
      };
    }

    if (options?.overrides?.project) {
      result.project = {
        ...result.project,
        ...this.omitUndefined(options.overrides.project),
      };
    }

    if (options?.overrides?.approvals) {
      result.approvals = options.overrides.approvals;
    }

    if (options?.overrides?.editValues !== undefined) {
      result.editValues = options.overrides.editValues;
    }

    if (options?.overrides?.richEditValues !== undefined) {
      result.richEditValues = options.overrides.richEditValues;
    }

    if (options?.overrides?.sectionBackgroundValues !== undefined) {
      result.sectionBackgroundValues = options.overrides.sectionBackgroundValues;
    }

    if (options?.overrides?.pageStyle !== undefined) {
      result.pageStyle = {
        ...(result.pageStyle || {}),
        ...options.overrides.pageStyle,
      };
    }

    return result;
  }

  async getFsdData(
    projectId: string,
    options?: FsdDataOptions,
  ): Promise<FsdDocumentModel> {
    let project = await this.queryFsdProject(projectId, true);

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const selectedEpicIds = options?.selectedEpicIds || [];
    const selectedFeatureIds = options?.selectedFeatureIds || [];
    const selectedUserStoryIds = options?.selectedUserStoryIds || [];

    const selectedEpicIdSet = new Set(selectedEpicIds);
    const selectedFeatureIdSet = new Set(selectedFeatureIds);
    const selectedUserStoryIdSet = new Set(selectedUserStoryIds);

    const shouldFilterByDescendants =
      selectedFeatureIdSet.size > 0 || selectedUserStoryIdSet.size > 0;
    const shouldFilterEpics =
      selectedEpicIdSet.size > 0 || shouldFilterByDescendants;

    const functionalRequirements: FsdDocumentModel['functionalRequirements'] = [];
    const systemFeatures: FsdDocumentModel['systemFeatures'] = [];
    const epics: NonNullable<FsdDocumentModel['epics']> = [];

    let requirementIndex = 1;

    const [screenshots, referenceDocumentsRaw, navigation, modules, rules, acceptance] =
      await Promise.all([
        this.prisma.fsdDashboardScreenshot.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdReferenceDocument.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdNavigationItem.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdFunctionalModule.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdBusinessRule.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdAcceptanceCriteria.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
      ]);

    const acceptanceCriteria = acceptance.map((criterion, index) => ({
      id: criterion.criteriaId || `AC-${index + 1}`,
      userStory: criterion.userStory || '',
      criterionDescription: this.deriveCriterionDescription(
        (criterion as { criterionDescription?: string }).criterionDescription,
        criterion.given,
        criterion.userStory,
        index,
      ),
      given: criterion.given || '',
      when: criterion.when || '',
      then: criterion.then || '',
      status: this.normalizeAcceptanceStatus(criterion.status),
    }));

    const acceptanceCriteriaByUserStory = new Map<string, string[]>();
    const acceptanceCriteriaDetailsByUserStory = new Map<
      string,
      Array<{
        id: string;
        userStory: string;
        criterionDescription: string;
        given: string;
        when: string;
        then: string;
        status: 'pass' | 'fail' | 'open';
      }>
    >();
    for (const criterion of acceptanceCriteria) {
      const key = criterion.userStory?.trim();
      if (!key) {
        continue;
      }

      const detail = {
        id: criterion.id,
        userStory: criterion.userStory,
        criterionDescription: criterion.criterionDescription,
        given: criterion.given,
        when: criterion.when,
        then: criterion.then,
        status: criterion.status,
      };

      const item = this.formatAcceptanceCriterion(
        criterion.given,
        criterion.when,
        criterion.then,
      );
      const list = acceptanceCriteriaByUserStory.get(key) || [];
      list.push(item);
      acceptanceCriteriaByUserStory.set(key, list);

      const details = acceptanceCriteriaDetailsByUserStory.get(key) || [];
      details.push(detail);
      acceptanceCriteriaDetailsByUserStory.set(key, details);
    }

    for (const epic of project.epics) {
      const selectedStoriesInEpic = epic.features.some((feature) =>
        feature.userStories.some((story) => selectedUserStoryIdSet.has(story.id)),
      );
      const selectedFeaturesInEpic = epic.features.some((feature) =>
        selectedFeatureIdSet.has(feature.id),
      );

      const includeEpic =
        !shouldFilterEpics ||
        selectedEpicIdSet.has(epic.id) ||
        selectedFeaturesInEpic ||
        selectedStoriesInEpic;

      if (!includeEpic) {
        continue;
      }

      const filteredFeatures = epic.features.filter((feature) => {
        if (!shouldFilterByDescendants) {
          return true;
        }

        const hasSelectedStories = feature.userStories.some((story) =>
          selectedUserStoryIdSet.has(story.id),
        );

        return selectedFeatureIdSet.has(feature.id) || hasSelectedStories;
      });

      const mappedFeatures = filteredFeatures.map((feature, featureIndex) => {
        const filteredStories = shouldFilterByDescendants
          ? feature.userStories.filter((story) => selectedUserStoryIdSet.has(story.id))
          : feature.userStories;

        const mappedUserStories = filteredStories.map((story, storyIndex) => {
          const storyAcceptanceRows = (
            story as {
              fsdAcceptanceCriteria?: Array<{
                criterionDescription?: string;
                given: string;
                when: string;
                then: string;
                status?: string;
              }>;
            }
          ).fsdAcceptanceCriteria;

          const storyRuleRows = (
            story as {
              fsdBusinessRules?: Array<{
                title: string;
                description: string;
              }>;
            }
          ).fsdBusinessRules;

          const storyIntegrationRows = (
            story as {
              fsdIntegrations?: Array<{
                action: string;
                integration: string;
              }>;
            }
          ).fsdIntegrations;

          const storyAcceptanceCriteria = storyAcceptanceRows?.length
            ? storyAcceptanceRows.map((criterion) =>
                this.formatAcceptanceCriterion(
                  criterion.given,
                  criterion.when,
                  criterion.then,
                ),
              )
            : acceptanceCriteriaByUserStory.get(story.id) ||
              acceptanceCriteriaByUserStory.get(story.name) ||
              [];

          const storyAcceptanceCriteriaDetails = storyAcceptanceRows?.length
            ? storyAcceptanceRows.map((criterion, criterionIndex) => ({
                id: `AC-${story.id}-${criterionIndex + 1}`,
                userStory: story.name,
                criterionDescription: this.deriveCriterionDescription(
                  criterion.criterionDescription,
                  criterion.given,
                  story.description || story.name,
                  criterionIndex,
                ),
                given: criterion.given || '',
                when: criterion.when || '',
                then: criterion.then || '',
                status: this.normalizeAcceptanceStatus(criterion.status),
              }))
            : acceptanceCriteriaDetailsByUserStory.get(story.id) ||
              acceptanceCriteriaDetailsByUserStory.get(story.name) ||
              [];

          const storyBusinessRules = storyRuleRows?.length
            ? storyRuleRows
            : rules.length > 0
              ? [rules[(featureIndex + storyIndex) % rules.length]]
              : [];

          const storyIntegrations = storyIntegrationRows?.length
            ? storyIntegrationRows
            : [
                {
                  action: `Traiter le parcours ${story.name}`,
                  integration: feature.name || epic.name || project.name,
                },
              ];

          return {
            id: story.id,
            title: this.normalizeUserStoryTitleAndDescription(story.name, story.description)
              .title,
            description: this.normalizeUserStoryTitleAndDescription(
              story.name,
              story.description,
            ).description,
            acceptanceCriteria: storyAcceptanceCriteria,
            acceptanceCriteriaDetails: storyAcceptanceCriteriaDetails,
            reglesDeGestion: storyBusinessRules.map(
              (rule) => rule.description || rule.title || '',
            ),
            gestion: storyIntegrations.map((item) => ({
              action: item.action || '',
              integration: item.integration || '',
            })),
            images: this.buildStoryImagesArray(story, options?.overrides?.excludedImageIds),
          };
        });

        return {
          id: `${epic.id}-F${String(featureIndex + 1).padStart(2, '0')}`,
          title: feature.name,
          description: feature.description || `Feature under epic ${epic.name}.`,
          userStories: mappedUserStories,
        };
      });

      epics.push({
        id: epic.id,
        title: epic.name,
        description: epic.description || `Epic ${epic.name}.`,
        features: mappedFeatures,
      });

      for (const feature of filteredFeatures) {
        const filteredStories = shouldFilterByDescendants
          ? feature.userStories.filter((story) => selectedUserStoryIdSet.has(story.id))
          : feature.userStories;

        systemFeatures.push({
          name: feature.name,
          description: feature.description || `Feature under epic ${epic.name}.`,
          userStories: filteredStories.map((story) => ({
            id: story.id,
            title: this.normalizeUserStoryTitleAndDescription(story.name, story.description)
              .title,
            description: this.normalizeUserStoryTitleAndDescription(
              story.name,
              story.description,
            ).description,
          })),
        });

        for (const story of filteredStories) {
          functionalRequirements.push({
            id: `FR-${String(requirementIndex).padStart(3, '0')}`,
            title:
              this.normalizeUserStoryTitleAndDescription(story.name, story.description)
                .title || 'No description provided.',
            description: this.normalizeUserStoryTitleAndDescription(
              story.name,
              story.description,
            ).description,
            priority: this.storyPriorityToFsdPriority(story.priority),
            relatedUserStory: story.id,
          });
          requirementIndex += 1;
        }
      }
    }

    const dashboardScreenshots = screenshots.map((item) => ({
      url: item.url || '',
      altText: item.altText || 'Dashboard preview',
      caption: item.caption || 'Aperçu du tableau de bord',
    }));

    const referenceDocuments = referenceDocumentsRaw.map((item) => ({
      name: item.name || '',
      type: item.type || '',
      attachment: item.attachment || '',
    }));

    const navigationItems = navigation.map((item) => ({
      label: item.label || '',
      targetPage: item.targetPage || '',
      type: item.type || '',
      accessRoles: item.accessRoles || '',
    }));

    const approvals = project.approvals.map((approval) => ({
      name: approval.approverName || '',
      role: approval.approverRole || '',
      date: approval.approvalDate.toISOString(),
    }));

    const glossary = project.fsdGlossaryEntries.map((entry) => ({
      term: entry.term || '',
      comment: entry.comment || '',
    }));

    const revisions = project.fsdRevisions.map((revision) => ({
      date: revision.date.toISOString(),
      version: revision.version || '',
      status: revision.status || '',
      author: revision.author || '',
    }));

    const functionalModules = modules.map((module) => ({
      title: module.title || '',
      description: module.description || '',
    }));

    const businessRules = rules.map((rule, index) => ({
      id: rule.ruleId || `BR-${index + 1}`,
      title: rule.title || `Règle ${index + 1}`,
      description: rule.description || '',
      source: rule.source || undefined,
      priority: rule.priority || undefined,
    }));

    const mappedEpicsWithAcceptance = epics.map((epic) => ({
      ...epic,
      features: epic.features.map((feature) => ({
        ...feature,
        userStories: feature.userStories.map((story) => ({
          ...story,
          acceptanceCriteria: story.acceptanceCriteria || [],
          acceptanceCriteriaDetails: story.acceptanceCriteriaDetails || [],
          reglesDeGestion: story.reglesDeGestion || [],
          gestion: story.gestion || [],
        })),
      })),
    }));

    // Apply global figure numbering to all story images
    this.applyGlobalFigureNumbering(mappedEpicsWithAcceptance);

    // Build canonical figures list from story images, with fallback to dashboardScreenshots
    const figures = this.buildFiguresList(mappedEpicsWithAcceptance, dashboardScreenshots);

    const functionalDescription = project.description || '';

    const model: FsdDocumentModel = {
      metadata: {
        title: `Functional Specification Document - ${project.name}`,
        projectName: project.name,
        clientName: project.name,
        version: '1.0',
        date: new Date().toISOString(),
        author: 'System',
      },
      editValues: {},
      richEditValues: {},
      sectionBackgroundValues: {},
      pageStyle: {
        backgroundColor: '#ffffff',
      },
      introduction: {
        purpose:
          project.description ||
          `Define functional scope and expected outcomes for ${project.name}.`,
        scope: `Epics, features, and user stories for ${project.name}.`,
        definitions: [],
      },
      overallDescription: {
        productPerspective:
          project.description ||
          `TestLab project ${project.name} functional scope.`,
        userClasses:
          'Business analysts, QA engineers, and product stakeholders.',
        assumptions:
          'Project data in TestLab is complete and maintained by delivery teams.',
      },
      projectOverview: project.description || '',
      methodology: '',
      glossary,
      revisions,
      functionalRequirements,
      nonFunctionalRequirements: {
        performance:
          'Document generation should complete in acceptable time for medium-sized projects.',
        security:
          'Only authorized users should access generated project documents.',
        usability:
          'Generated documents should be readable and consistent across export formats.',
      },
      systemFeatures,
      epics: mappedEpicsWithAcceptance,
      externalInterfaces: {
        userInterface: 'TestLab back-office web application.',
        apiInterfaces: 'NestJS REST endpoints and PostgreSQL data source.',
      },
      approvals,
      referenceDocuments,
      dashboardScreenshots,
      figures,
      navigationItems,
      functionalDescription,
      functionalModules,
      businessRules,
      acceptanceCriteria,
      template: this.defaultTemplate,
    };

    if (options?.overrides?.metadata) {
      model.metadata = {
        ...model.metadata,
        ...this.omitUndefined(options.overrides.metadata),
      };
    }

    if (options?.overrides?.introduction) {
      model.introduction = {
        ...model.introduction,
        ...this.omitUndefined(options.overrides.introduction),
      };
    }

    if (options?.overrides?.overallDescription) {
      model.overallDescription = {
        ...model.overallDescription,
        ...this.omitUndefined(options.overrides.overallDescription),
      };
    }

    if (options?.overrides?.projectOverview !== undefined) {
      model.projectOverview = options.overrides.projectOverview;
    }

    if (options?.overrides?.methodology !== undefined) {
      model.methodology = options.overrides.methodology;
    }

    if (options?.overrides?.approvals !== undefined) {
      model.approvals = options.overrides.approvals;
    }

    if (options?.overrides?.referenceDocuments !== undefined) {
      model.referenceDocuments = options.overrides.referenceDocuments;
    }

    if (options?.overrides?.glossary !== undefined) {
      model.glossary = options.overrides.glossary;
    }

    if (options?.overrides?.revisions !== undefined) {
      model.revisions = options.overrides.revisions;
    }

    if (options?.overrides?.editValues !== undefined) {
      model.editValues = options.overrides.editValues;
    }

    if (options?.overrides?.richEditValues !== undefined) {
      model.richEditValues = options.overrides.richEditValues;
    }

    if (options?.overrides?.sectionBackgroundValues !== undefined) {
      model.sectionBackgroundValues = options.overrides.sectionBackgroundValues;
    }

    if (options?.overrides?.pageStyle !== undefined) {
      model.pageStyle = {
        ...(model.pageStyle || {}),
        ...options.overrides.pageStyle,
      };
    }

    if (model.introduction.definitions) {
      model.introduction.definitions = model.introduction.definitions.filter(
        (item) => item.term.trim() || item.definition.trim(),
      );
    }

    if (model.glossary) {
      model.glossary = model.glossary.filter(
        (item) => item.term.trim() || item.comment.trim(),
      );
    }

    if (model.revisions) {
      model.revisions = model.revisions.filter(
        (item) =>
          item.date.trim() ||
          item.version.trim() ||
          item.status.trim() ||
          item.author.trim(),
      );
    }

    return model;
  }

  private normalizeAcceptanceStatus(value: unknown): 'pass' | 'fail' | 'open' {
    const normalized = String(value || '')
      .toLowerCase()
      .trim();
    if (normalized === 'pass' || normalized === 'fail' || normalized === 'open') {
      return normalized;
    }

    return 'open';
  }

  /**
   * Build images array for a story, including legacy attachment fallback.
   * Returns FsdUserStory.images format with url, caption, alt.
   */
  private extractImageFilename(url: string): string {
    const trimmed = String(url || '').trim();
    if (!trimmed) {
      return '';
    }

    const withoutQuery = trimmed.split(/[?#]/)[0];
    const lastSegment = withoutQuery.split('/').pop() || '';

    if (!lastSegment) {
      return trimmed;
    }

    try {
      return decodeURIComponent(lastSegment);
    } catch {
      return lastSegment;
    }
  }

  private resolveImageTitle(input: {
    caption?: string;
    alt?: string;
    url?: string;
  }): string {
    const caption = typeof input.caption === 'string' ? input.caption.trim() : '';
    if (caption) {
      return caption;
    }

    const alt = typeof input.alt === 'string' ? input.alt.trim() : '';
    if (alt) {
      return alt;
    }

    const url = typeof input.url === 'string' ? input.url.trim() : '';
    if (!url) {
      return '';
    }

    const filename = this.extractImageFilename(url);
    return filename || url;
  }

    private buildStoryImagesArray(
    story: any,
    excludedImageIds?: string[],
  ): Array<{
    url: string;
    alt?: string;
    caption?: string;
    figureNumber?: string;
    figureTitle?: string;
  }> {
    const excludedSet = new Set(excludedImageIds ?? []);
    const images: Array<{
      url: string;
      alt?: string;
      caption?: string;
      figureNumber?: string;
      figureTitle?: string;
    }> = [];

    // Include new multi-image records (skip excluded)
    if (story.fsdImages && story.fsdImages.length > 0) {
      for (const img of story.fsdImages) {
        if (excludedSet.has(img.id)) {
          continue; 
        }
        const figureTitle = this.resolveImageTitle({
          caption: img.caption,
          alt: img.altText,
          url: img.url,
        });
        images.push({
          url: img.url,
          alt: img.altText,
          caption: img.caption || '',
          figureTitle,
        });
      }
    }

    // Legacy attachment fallback (unchanged)
    const hasFsdImages = story.fsdImages && story.fsdImages.length > 0;
    const attachment = story?.attachment;
    if (images.length === 0 && !hasFsdImages && attachment && typeof attachment === 'string' && attachment.trim()) {
      const figureTitle = this.resolveImageTitle({
        caption: story.name,
        alt: story.name,
        url: attachment.trim(),
      });
      images.push({
        url: attachment.trim(),
        alt: story.name || '',
        caption: story.name || '',
        figureTitle,
      });
    }

    return images;
  }


  private applyGlobalFigureNumbering(epics: any[]): any[] {
    let globalFigureNumber = 1;

    for (const epic of epics) {
      for (const feature of epic.features) {
        for (const story of feature.userStories) {
          if (story.images && story.images.length > 0) {
            for (const image of story.images) {
              image.figureNumber = `${globalFigureNumber}`;
              // Preserve original caption as figureTitle (don't overwrite with "Figure N")
              if (!image.figureTitle) {
                image.figureTitle = this.resolveImageTitle({
                  caption: image.caption,
                  alt: image.alt || image.altText,
                  url: image.url,
                });
              }
              globalFigureNumber++;
            }
          }
        }
      }
    }

    return epics;
  }

  /**
   * Build canonical figures list from story images after global numbering.
   * Collects all images from epics -> features -> userStories in deterministic order.
   * Fallback to dashboardScreenshots if no story images are available.
   */
  private buildFiguresList(epics: any[], dashboardScreenshots: any[]): Array<{ figureNumber: string; figureTitle: string }> {
    const figures: Array<{ figureNumber: string; figureTitle: string }> = [];

    // Collect figures from story images
    for (const epic of epics) {
      for (const feature of epic.features) {
        for (const story of feature.userStories) {
          if (story.images && story.images.length > 0) {
            for (const image of story.images) {
              if (image.figureNumber) {
                figures.push({
                  figureNumber: image.figureNumber,
                  figureTitle: this.resolveImageTitle({
                    caption: image.figureTitle || image.caption,
                    alt: image.alt || image.altText,
                    url: image.url,
                  }),
                });
              }
            }
          }
        }
      }
    }

    // Fallback to dashboardScreenshots if no story images were found
    if (figures.length === 0 && dashboardScreenshots && dashboardScreenshots.length > 0) {
      dashboardScreenshots.forEach((item, index) => {
        figures.push({
          figureNumber: `${index + 1}`,
          figureTitle: this.resolveImageTitle({
            caption: item.caption,
            alt: item.altText,
            url: item.url,
          }),
        });
      });
    }

    return figures;
  }

  private async queryFsdProject(
    projectId: string,
    withStoryRelations: boolean,
  ): Promise<any> {
    if (!withStoryRelations) {
      return this.prisma.project.findUnique({
        where: { id: projectId },
        include: {
          approvals: {
            orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
          },
          fsdGlossaryEntries: {
            orderBy: [{ order: 'asc' }, { id: 'asc' }],
          },
          fsdRevisions: {
            orderBy: [{ order: 'asc' }, { id: 'asc' }],
          },
          epics: {
            orderBy: [{ creationDate: 'asc' }],
            include: {
              features: {
                orderBy: [{ creationDate: 'asc' }],
                include: {
                  userStories: {
                    orderBy: [{ creationDate: 'asc' }],
                  },
                },
              },
            },
          },
        },
      });
    }

    try {
      return await this.prisma.project.findUnique({
        where: { id: projectId },
        include: {
          approvals: {
            orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
          },
          fsdGlossaryEntries: {
            orderBy: [{ order: 'asc' }, { id: 'asc' }],
          },
          fsdRevisions: {
            orderBy: [{ order: 'asc' }, { id: 'asc' }],
          },
          epics: {
            orderBy: [{ creationDate: 'asc' }],
            include: {
              features: {
                orderBy: [{ creationDate: 'asc' }],
                include: {
                  userStories: {
                    orderBy: [{ creationDate: 'asc' }],
                    include: {
                      fsdAcceptanceCriteria: {
                        orderBy: [{ order: 'asc' }, { id: 'asc' }],
                      },
                      fsdBusinessRules: {
                        orderBy: [{ order: 'asc' }, { id: 'asc' }],
                      },
                      fsdIntegrations: {
                        orderBy: [{ order: 'asc' }, { id: 'asc' }],
                      },
                      fsdImages: {
                        orderBy: [{ order: 'asc' }, { createdAt: 'asc' }],
                      },
                    },
                  },
                },
              },
            },
          },
        },
      });
    } catch (error) {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        (error.code === 'P2021' || error.code === 'P2022')
      ) {
        return this.queryFsdProject(projectId, false);
      }

      throw error;
    }
  }

  private formatAcceptanceCriterion(
    given: string,
    when: string,
    then: string,
  ): string {
    const normalizedGiven = given
      .trim()
      .replace(/^étant donné qu(?:e|['’])\s*/i, '')
      .replace(/^que\s+/i, '');
    const normalizedWhen = when.trim().replace(/^quand\s+/i, '');
    const normalizedThen = then.trim().replace(/^alors\s+/i, '');
    const whenPrefix = /^[aeiouyhàâæéèêëîïôœùûü]/i.test(normalizedWhen)
      ? 'Lorsqu’'
      : 'Lorsque ';

    return [
      `Étant donné que ${normalizedGiven}`,
      `${whenPrefix}${normalizedWhen}`,
      `Alors ${normalizedThen}`,
    ].join('\n');
  }

  private isUuidLike(value: string): boolean {
    return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(
      value.trim(),
    );
  }

  private deriveCriterionDescription(
    rawDescription: string | undefined,
    given: string | undefined,
    fallbackLabel: string | undefined,
    index: number,
  ): string {
    const explicit = String(rawDescription || '').trim();
    if (explicit && !this.isUuidLike(explicit)) {
      return explicit;
    }

    const normalizedGiven = String(given || '')
      .trim()
      .replace(/^étant donné qu(?:e|['’])\s*/i, '')
      .replace(/^que\s+/i, '');

    if (normalizedGiven) {
      return normalizedGiven.slice(0, 140);
    }

    const fallback = String(fallbackLabel || '').trim();
    if (fallback && !this.isUuidLike(fallback)) {
      return fallback;
    }

    return `Critère ${index + 1}`;
  }

  private normalizeUserStoryTitleAndDescription(
    name: string | undefined,
    description: string | undefined,
  ): {
    title: string;
    description: string;
  } {
    const normalizedName = String(name || '').trim();
    const normalizedDescription = String(description || '').trim();

    const looksLikeNarrative = (value: string) => /^en tant que\b/i.test(value);

    const narrative = looksLikeNarrative(normalizedDescription)
      ? normalizedDescription
      : looksLikeNarrative(normalizedName)
        ? normalizedName
        : '';

    const titleCandidates = [normalizedDescription, normalizedName]
      .filter((value) => value.length > 0)
      .filter((value) => !looksLikeNarrative(value));

    const title =
      titleCandidates.sort((a, b) => a.length - b.length)[0] ||
      normalizedDescription ||
      normalizedName ||
      'User story';

    return {
      title,
      description: narrative || normalizedDescription || normalizedName || title,
    };
  }

  private storyPriorityToFsdPriority(value: string): 'Critical' | 'High' | 'Medium' | 'Low' {
    const normalized = String(value || '').toUpperCase();

    if (normalized === 'HIGH') {
      return 'High';
    }

    if (normalized === 'LOW') {
      return 'Low';
    }

    return 'Medium';
  }

  private projectNumericId(projectId: string): number {
    const digits = projectId.replace(/\D/g, '');
    if (digits.length) {
      const parsed = Number.parseInt(digits.slice(0, 9), 10);
      if (Number.isInteger(parsed) && parsed > 0) {
        return parsed;
      }
    }

    let hash = 0;
    for (const char of projectId) {
      hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
    }

    return hash || 1;
  }

  private resolveAuthor(): string {
    return process.env.DOCUMENT_AUTHOR || process.env.USERNAME || 'System';
  }

  private omitUndefined<T extends Record<string, unknown>>(value: T): Partial<T> {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);
    return Object.fromEntries(entries) as Partial<T>;
  }

  private filterSelectedSuites(
    suites: CahierDocumentModel['suites'],
    selectedSuiteIds: Set<string>,
  ): CahierDocumentModel['suites'] {
    return suites
      .map((suite) => {
        const children = this.filterSelectedSuites(suite.children, selectedSuiteIds);
        const isSelected = selectedSuiteIds.has(suite.id);

        if (!isSelected && children.length === 0 && suite.testCases.length === 0) {
          return null;
        }

        return {
          ...suite,
          children,
        };
      })
      .filter((suite): suite is CahierDocumentModel['suites'][number] => suite !== null);
  }

  private filterSuitesBySelectedTestCases(
    suites: CahierDocumentModel['suites'],
    selectedTestCaseIds: Set<string>,
  ): CahierDocumentModel['suites'] {
    return suites
      .map((suite) => {
        const children = this.filterSuitesBySelectedTestCases(
          suite.children,
          selectedTestCaseIds,
        );
        const testCases = suite.testCases.filter((testCase) =>
          selectedTestCaseIds.has(testCase.id),
        );

        if (children.length === 0 && testCases.length === 0) {
          return null;
        }

        return {
          ...suite,
          children,
          testCases,
        };
      })
      .filter((suite): suite is CahierDocumentModel['suites'][number] => suite !== null);
  }

  private async ensureProjectExists(projectId: string): Promise<void> {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      select: { id: true },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }
  }
}
