import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import type {
  CahierDocumentModel,
  DocumentTemplateSnapshot,
  FsdDocumentModel,
} from '../interfaces/document-model.interface';

function formatDate(date: Date): string {
  return date.toLocaleDateString('fr-FR');
}

@Injectable()
export class DocumentDataService {
  constructor(private readonly prisma: PrismaService) {}

  private readonly defaultTemplate: DocumentTemplateSnapshot = {
    id: 'default',
    name: 'Default Template',
    title: 'Project Quality Report',
    footer: 'Generated by TestLab Documents Module',
    showStatistics: true,
    showExecutions: true,
    showPreconditions: true,
    showSteps: true,
    showApprovals: true,
    showContext: true,
    failedOnly: false,
  };

  getTemplates(): DocumentTemplateSnapshot[] {
    return [
      this.defaultTemplate,
      {
        ...this.defaultTemplate,
        id: 'compact',
        name: 'Compact Template',
        title: 'Compact Test Summary',
        showExecutions: false,
        showPreconditions: false,
        showApprovals: false,
      },
    ];
  }

  async getCahierData(projectId: string): Promise<CahierDocumentModel> {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      include: {
        approvals: {
          orderBy: [{ createdAt: 'asc' }],
        },
        testSuites: {
          orderBy: [{ order: 'asc' }, { name: 'asc' }],
          include: {
            testCases: {
              include: {
                preconditions: { orderBy: [{ order: 'asc' }] },
                steps: { orderBy: [{ order: 'asc' }] },
              },
              orderBy: [{ name: 'asc' }],
            },
          },
        },
      },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const suitesByParent = new Map<string | null, typeof project.testSuites>();

    for (const suite of project.testSuites) {
      const key = suite.parentId ?? null;
      const existing = suitesByParent.get(key) ?? [];
      existing.push(suite);
      suitesByParent.set(key, existing);
    }

    const buildSuite = (suite: (typeof project.testSuites)[number]): CahierDocumentModel['suites'][number] => {
      const children = (suitesByParent.get(suite.id) ?? [])
        .sort((a, b) => {
          const ao = a.order ?? Number.MAX_SAFE_INTEGER;
          const bo = b.order ?? Number.MAX_SAFE_INTEGER;
          if (ao !== bo) return ao - bo;
          return a.name.localeCompare(b.name);
        })
        .map(buildSuite);

      return {
        id: suite.id,
        name: suite.name,
        order: suite.order,
        children,
        testCases: suite.testCases.map((testCase) => ({
          id: testCase.id,
          code: `TC-${testCase.id.slice(0, 8)}`,
          name: testCase.name,
          summary: testCase.summary || 'No summary provided.',
          preconditions: testCase.preconditions.map((precondition, index) => ({
            content: precondition.content,
            order: precondition.order ?? index + 1,
          })),
          steps: testCase.steps.map((step, index) => ({
            order: step.order ?? index + 1,
            action: step.action,
            expectedResult: step.expectedResult,
          })),
        })),
      };
    };

    const rootSuites = (suitesByParent.get(null) ?? [])
      .sort((a, b) => {
        const ao = a.order ?? Number.MAX_SAFE_INTEGER;
        const bo = b.order ?? Number.MAX_SAFE_INTEGER;
        if (ao !== bo) return ao - bo;
        return a.name.localeCompare(b.name);
      })
      .map(buildSuite);

    const result: CahierDocumentModel = {
      metadata: {
        title: `Cahier de Recette - ${project.name}`,
        clientName: project.clientName || project.name,
        author: this.resolveAuthor(),
        version: '1.0',
        date: formatDate(new Date()),
      },
      context: {
        description:
          project.description ||
          `Cahier de recette generated from project ${project.name}.`,
        objective: `Validate test scenarios and expected outcomes for ${project.name}.`,
      },
      project: {
        id: this.projectNumericId(project.id),
        name: project.name,
        owner: project.projectOwner || 'N/A',
        openDefects: project.openDefects,
      },
      suites: rootSuites,
      approvals: project.approvals.map((approval) => ({
        // Keep legacy keys and add new aliases for DOCX placeholders.
        name: approval.approverName,
        role: approval.approverRole,
        date: formatDate(approval.approvalDate),
        approverName: approval.approverName,
        approverRole: approval.approverRole,
        approvalDate: formatDate(approval.approvalDate),
      })),
      template: this.defaultTemplate,
    };

    console.log('FINAL DOCUMENT DATA:', JSON.stringify(result, null, 2));

    return result;
  }

  async getFsdData(projectId: string): Promise<FsdDocumentModel> {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      include: {
        epics: {
          orderBy: [{ creationDate: 'asc' }],
          include: {
            features: {
              orderBy: [{ creationDate: 'asc' }],
              include: {
                userStories: {
                  orderBy: [{ creationDate: 'asc' }],
                },
              },
            },
          },
        },
      },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const functionalRequirements: FsdDocumentModel['functionalRequirements'] = [];
    const systemFeatures: FsdDocumentModel['systemFeatures'] = [];

    let requirementIndex = 1;

    for (const epic of project.epics) {
      for (const feature of epic.features) {
        systemFeatures.push({
          name: feature.name,
          description: feature.description || `Feature under epic ${epic.name}.`,
          userStories: feature.userStories.map((story) => ({
            id: story.id,
            title: story.name,
            description: story.description || 'No description provided.',
          })),
        });

        for (const story of feature.userStories) {
          functionalRequirements.push({
            id: `FR-${String(requirementIndex).padStart(3, '0')}`,
            title: story.name,
            description: story.description || 'No description provided.',
            priority: this.storyPriorityToFsdPriority(story.priority),
            relatedUserStory: story.id,
          });
          requirementIndex += 1;
        }
      }
    }

    return {
      metadata: {
        title: `Functional Specification Document - ${project.name}`,
        projectName: project.name,
        clientName: project.name,
        version: '1.0',
        date: new Date().toISOString(),
        author: 'System',
      },
      introduction: {
        purpose:
          project.description ||
          `Define functional scope and expected outcomes for ${project.name}.`,
        scope: `Epics, features, and user stories for ${project.name}.`,
        definitions: [],
      },
      overallDescription: {
        productPerspective:
          project.description ||
          `TestLab project ${project.name} functional scope.`,
        userClasses:
          'Business analysts, QA engineers, and product stakeholders.',
        assumptions:
          'Project data in TestLab is complete and maintained by delivery teams.',
      },
      functionalRequirements,
      nonFunctionalRequirements: {
        performance:
          'Document generation should complete in acceptable time for medium-sized projects.',
        security:
          'Only authorized users should access generated project documents.',
        usability:
          'Generated documents should be readable and consistent across export formats.',
      },
      systemFeatures,
      externalInterfaces: {
        userInterface: 'TestLab back-office web application.',
        apiInterfaces: 'NestJS REST endpoints and PostgreSQL data source.',
      },
      approvals: [],
      template: this.defaultTemplate,
    };
  }

  private storyPriorityToFsdPriority(value: string): 'Critical' | 'High' | 'Medium' | 'Low' {
    const normalized = String(value || '').toUpperCase();

    if (normalized === 'HIGH') {
      return 'High';
    }

    if (normalized === 'LOW') {
      return 'Low';
    }

    return 'Medium';
  }

  private projectNumericId(projectId: string): number {
    const digits = projectId.replace(/\D/g, '');
    if (digits.length) {
      const parsed = Number.parseInt(digits.slice(0, 9), 10);
      if (Number.isInteger(parsed) && parsed > 0) {
        return parsed;
      }
    }

    let hash = 0;
    for (const char of projectId) {
      hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
    }

    return hash || 1;
  }

  private resolveAuthor(): string {
    return process.env.DOCUMENT_AUTHOR || process.env.USERNAME || 'System';
  }
}
