import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import type {
  CahierSelectionSuiteDto,
  FsdSelectionEpicDto,
} from '../dto/document-selection.dto';
import type {
  CahierDocumentModel,
  DocumentTemplateSnapshot,
  FsdDocumentModel,
} from '../interfaces/document-model.interface';

type FsdDataOverrides = {
  metadata?: Partial<FsdDocumentModel['metadata']>;
  introduction?: Partial<FsdDocumentModel['introduction']>;
  overallDescription?: Partial<FsdDocumentModel['overallDescription']>;
  projectOverview?: string;
  methodology?: string;
  glossary?: FsdDocumentModel['glossary'];
  revisions?: FsdDocumentModel['revisions'];
  editValues?: Record<string, string>;
};

type FsdDataOptions = {
  selectedEpicIds?: string[];
  selectedFeatureIds?: string[];
  selectedUserStoryIds?: string[];
  overrides?: FsdDataOverrides;
};

type PersistFsdStepTwoInput = {
  approvals?: Array<{
    name?: string;
    role?: string;
    date?: string;
  }>;
  referenceDocuments?: Array<{
    name?: string;
    type?: string;
    attachment?: string;
  }>;
  glossary?: Array<{
    term?: string;
    comment?: string;
  }>;
  revisions?: Array<{
    date?: string;
    version?: string;
    status?: string;
    authors?: string[];
    author?: string;
  }>;
};

function normalizeAuthors(authors?: string[], author?: string): string[] {
  const normalized = (authors || [])
    .map((item) => (item || '').trim())
    .filter((item) => item.length > 0);

  if (normalized.length > 0) {
    return normalized;
  }

  if (author?.trim()) {
    return [author.trim()];
  }

  return [];
}

type CahierDataOverrides = {
  metadata?: Partial<CahierDocumentModel['metadata']>;
  context?: Partial<CahierDocumentModel['context']>;
  project?: Partial<CahierDocumentModel['project']>;
  approvals?: CahierDocumentModel['approvals'];
};

type CahierDataOptions = {
  selectedSuiteIds?: string[];
  selectedTestCaseIds?: string[];
  overrides?: CahierDataOverrides;
};

function formatDate(date: Date): string {
  return date.toLocaleDateString('fr-FR');
}

@Injectable()
export class DocumentDataService {
  constructor(private readonly prisma: PrismaService) {}

  private readonly defaultTemplate: DocumentTemplateSnapshot = {
    id: 'default',
    name: 'Default Template',
    title: 'Project Quality Report',
    footer: 'Generated by TestLab Documents Module',
    showStatistics: true,
    showExecutions: true,
    showPreconditions: true,
    showSteps: true,
    showApprovals: true,
    showContext: true,
    failedOnly: false,
  };

  getTemplates(): DocumentTemplateSnapshot[] {
    return [
      this.defaultTemplate,
      {
        ...this.defaultTemplate,
        id: 'compact',
        name: 'Compact Template',
        title: 'Compact Test Summary',
        showExecutions: false,
        showPreconditions: false,
        showApprovals: false,
      },
    ];
  }

  async persistFsdStepTwoData(
    projectId: string,
    payload: PersistFsdStepTwoInput,
  ): Promise<void> {
    await this.ensureProjectExists(projectId);

    const approvals = (payload.approvals || [])
      .filter(
        (approval) =>
          approval.name?.trim() &&
          approval.role?.trim() &&
          approval.date?.trim(),
      )
      .map((approval) => {
        const parsedDate = approval.date ? new Date(approval.date) : null;
        return {
          projectId,
          approverName: approval.name!.trim(),
          approverRole: approval.role!.trim(),
          approvalDate:
            parsedDate && !Number.isNaN(parsedDate.getTime())
              ? parsedDate
              : new Date(),
        };
      });

    const referenceDocuments = (payload.referenceDocuments || [])
      .filter(
        (item) =>
          item.name?.trim() && item.type?.trim() && item.attachment?.trim(),
      )
      .map((item, index) => ({
        projectId,
        name: item.name!.trim(),
        type: item.type!.trim(),
        attachment: item.attachment!.trim(),
        order: index,
      }));

    const glossaryEntries = (payload.glossary || [])
      .filter((item) => item.term?.trim() && item.comment?.trim())
      .map((item, index) => ({
        projectId,
        term: item.term!.trim(),
        comment: item.comment!.trim(),
        order: index,
      }));

    const revisions = (payload.revisions || [])
      .filter(
        (item) =>
          item.date?.trim() &&
          item.version?.trim() &&
          item.status?.trim() &&
          normalizeAuthors(item.authors, item.author).length > 0,
      )
      .map((item, index) => {
        const parsedDate = item.date ? new Date(item.date) : null;
        const normalizedAuthors = normalizeAuthors(item.authors, item.author);
        return {
          projectId,
          date:
            parsedDate && !Number.isNaN(parsedDate.getTime())
              ? parsedDate
              : new Date(),
          version: item.version!.trim(),
          status: item.status!.trim(),
          author: normalizedAuthors.join('; '),
          order: index,
        };
      });

    await this.prisma.$transaction(async (tx) => {
      if (payload.approvals !== undefined) {
        await tx.documentApproval.deleteMany({ where: { projectId } });
        if (approvals.length > 0) {
          await tx.documentApproval.createMany({ data: approvals });
        }
      }

      if (payload.referenceDocuments !== undefined) {
        await tx.fsdReferenceDocument.deleteMany({ where: { projectId } });
        if (referenceDocuments.length > 0) {
          await tx.fsdReferenceDocument.createMany({ data: referenceDocuments });
        }
      }

      if (payload.glossary !== undefined) {
        await tx.fsdGlossary.deleteMany({ where: { projectId } });
        if (glossaryEntries.length > 0) {
          await tx.fsdGlossary.createMany({ data: glossaryEntries });
        }
      }

      if (payload.revisions !== undefined) {
        await tx.fsdRevision.deleteMany({ where: { projectId } });
        if (revisions.length > 0) {
          await tx.fsdRevision.createMany({ data: revisions });
        }
      }
    });
  }

  async getSelectableEpicsForFsd(projectId: string): Promise<FsdSelectionEpicDto[]> {
    await this.ensureProjectExists(projectId);

    const epics = await this.prisma.epic.findMany({
      where: { projectId },
      orderBy: [{ creationDate: 'asc' }, { name: 'asc' }],
      include: {
        _count: {
          select: { features: true },
        },
        features: {
          orderBy: [{ creationDate: 'asc' }, { name: 'asc' }],
          select: {
            id: true,
            name: true,
            _count: {
              select: { userStories: true },
            },
            userStories: {
              orderBy: [{ creationDate: 'asc' }, { name: 'asc' }],
              select: {
                id: true,
                name: true,
                description: true,
              },
            },
          },
        },
      },
    });

    return epics.map((epic) => ({
      id: epic.id,
      name: epic.name,
      featureCount: epic._count.features,
      userStoryCount: epic.features.reduce(
        (total, feature) => total + feature._count.userStories,
        0,
      ),
      features: epic.features.map((feature) => ({
        id: feature.id,
        name: feature.name,
        userStoryCount: feature._count.userStories,
        userStories: feature.userStories.map((story) => ({
          id: story.id,
          name: story.description?.trim() ? story.description : story.name,
        })),
      })),
    }));
  }

  async getSelectableSuitesForCahier(
    projectId: string,
  ): Promise<CahierSelectionSuiteDto[]> {
    await this.ensureProjectExists(projectId);

    const suites = await this.prisma.testSuite.findMany({
      where: { projectId },
      orderBy: [{ order: 'asc' }, { name: 'asc' }],
      include: {
        testCases: {
          orderBy: [{ name: 'asc' }],
          select: {
            id: true,
            name: true,
          },
        },
        _count: {
          select: {
            testCases: true,
            children: true,
          },
        },
      },
    });

    return suites.map((suite) => ({
      id: suite.id,
      name: suite.name,
      order: suite.order,
      parentId: suite.parentId,
      testCaseCount: suite._count.testCases,
      childSuiteCount: suite._count.children,
      testCases: suite.testCases.map((testCase) => ({
        id: testCase.id,
        name: testCase.name,
      })),
    }));
  }

  async getCahierData(
    projectId: string,
    options?: CahierDataOptions,
  ): Promise<CahierDocumentModel> {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      include: {
        approvals: {
          orderBy: [{ createdAt: 'asc' }],
        },
        testSuites: {
          orderBy: [{ order: 'asc' }, { name: 'asc' }],
          include: {
            testCases: {
              include: {
                preconditions: { orderBy: [{ order: 'asc' }] },
                steps: { orderBy: [{ order: 'asc' }] },
              },
              orderBy: [{ name: 'asc' }],
            },
          },
        },
      },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const suitesByParent = new Map<string | null, typeof project.testSuites>();

    for (const suite of project.testSuites) {
      const key = suite.parentId ?? null;
      const existing = suitesByParent.get(key) ?? [];
      existing.push(suite);
      suitesByParent.set(key, existing);
    }

    const buildSuite = (suite: (typeof project.testSuites)[number]): CahierDocumentModel['suites'][number] => {
      const children = (suitesByParent.get(suite.id) ?? [])
        .sort((a, b) => {
          const ao = a.order ?? Number.MAX_SAFE_INTEGER;
          const bo = b.order ?? Number.MAX_SAFE_INTEGER;
          if (ao !== bo) return ao - bo;
          return a.name.localeCompare(b.name);
        })
        .map(buildSuite);

      return {
        id: suite.id,
        name: suite.name,
        order: suite.order,
        children,
        testCases: suite.testCases.map((testCase) => ({
          id: testCase.id,
          code: `TC-${testCase.id.slice(0, 8)}`,
          name: testCase.name,
          summary: testCase.summary || 'No summary provided.',
          preconditions: testCase.preconditions.map((precondition, index) => ({
            content: precondition.content,
            order: precondition.order ?? index + 1,
          })),
          steps: testCase.steps.map((step, index) => ({
            order: step.order ?? index + 1,
            action: step.action,
            expectedResult: step.expectedResult,
          })),
        })),
      };
    };

    const rootSuites = (suitesByParent.get(null) ?? [])
      .sort((a, b) => {
        const ao = a.order ?? Number.MAX_SAFE_INTEGER;
        const bo = b.order ?? Number.MAX_SAFE_INTEGER;
        if (ao !== bo) return ao - bo;
        return a.name.localeCompare(b.name);
      })
      .map(buildSuite);

    const selectedSuiteIds = new Set(options?.selectedSuiteIds ?? []);
    const selectedTestCaseIds = new Set(options?.selectedTestCaseIds ?? []);
    const shouldFilterTestCases = selectedTestCaseIds.size > 0;

    const suitesWithSelectedTestCases = shouldFilterTestCases
      ? this.filterSuitesBySelectedTestCases(rootSuites, selectedTestCaseIds)
      : rootSuites;

    const filteredSuites =
      selectedSuiteIds.size > 0
        ? this.filterSelectedSuites(suitesWithSelectedTestCases, selectedSuiteIds)
        : suitesWithSelectedTestCases;

    const result: CahierDocumentModel = {
      metadata: {
        title: `Cahier de Recette - ${project.name}`,
        clientName: project.clientName || project.name,
        author: this.resolveAuthor(),
        version: '1.0',
        date: formatDate(new Date()),
      },
      context: {
        description:
          project.description ||
          `Cahier de recette generated from project ${project.name}.`,
        objective: `Validate test scenarios and expected outcomes for ${project.name}.`,
      },
      project: {
        id: this.projectNumericId(project.id),
        name: project.name,
        owner: project.projectOwner || 'N/A',
        openDefects: project.openDefects,
      },
      suites: filteredSuites,
      approvals: project.approvals.map((approval) => ({
        // Keep legacy keys and add new aliases for DOCX placeholders.
        name: approval.approverName,
        role: approval.approverRole,
        date: formatDate(approval.approvalDate),
        approverName: approval.approverName,
        approverRole: approval.approverRole,
        approvalDate: formatDate(approval.approvalDate),
      })),
      template: this.defaultTemplate,
    };

    if (options?.overrides?.metadata) {
      result.metadata = {
        ...result.metadata,
        ...this.omitUndefined(options.overrides.metadata),
      };
    }

    if (options?.overrides?.context) {
      result.context = {
        ...result.context,
        ...this.omitUndefined(options.overrides.context),
      };
    }

    if (options?.overrides?.project) {
      result.project = {
        ...result.project,
        ...this.omitUndefined(options.overrides.project),
      };
    }

    if (options?.overrides?.approvals) {
      result.approvals = options.overrides.approvals;
    }

    return result;
  }

  async getFsdData(
    projectId: string,
    options?: FsdDataOptions,
  ): Promise<FsdDocumentModel> {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      include: {
        approvals: {
          orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
        },
        fsdGlossaryEntries: {
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        },
        fsdRevisions: {
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        },
        epics: {
          orderBy: [{ creationDate: 'asc' }],
          include: {
            features: {
              orderBy: [{ creationDate: 'asc' }],
              include: {
                userStories: {
                  orderBy: [{ creationDate: 'asc' }],
                },
              },
            },
          },
        },
      },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const selectedEpicIds = options?.selectedEpicIds || [];
    const selectedFeatureIds = options?.selectedFeatureIds || [];
    const selectedUserStoryIds = options?.selectedUserStoryIds || [];

    const selectedEpicIdSet = new Set(selectedEpicIds);
    const selectedFeatureIdSet = new Set(selectedFeatureIds);
    const selectedUserStoryIdSet = new Set(selectedUserStoryIds);

    const shouldFilterByDescendants =
      selectedFeatureIdSet.size > 0 || selectedUserStoryIdSet.size > 0;
    const shouldFilterEpics =
      selectedEpicIdSet.size > 0 || shouldFilterByDescendants;

    const functionalRequirements: FsdDocumentModel['functionalRequirements'] = [];
    const systemFeatures: FsdDocumentModel['systemFeatures'] = [];
    const epics: NonNullable<FsdDocumentModel['epics']> = [];

    let requirementIndex = 1;

    for (const epic of project.epics) {
      const selectedStoriesInEpic = epic.features.some((feature) =>
        feature.userStories.some((story) => selectedUserStoryIdSet.has(story.id)),
      );
      const selectedFeaturesInEpic = epic.features.some((feature) =>
        selectedFeatureIdSet.has(feature.id),
      );

      const includeEpic =
        !shouldFilterEpics ||
        selectedEpicIdSet.has(epic.id) ||
        selectedFeaturesInEpic ||
        selectedStoriesInEpic;

      if (!includeEpic) {
        continue;
      }

      const filteredFeatures = epic.features.filter((feature) => {
        if (!shouldFilterByDescendants) {
          return true;
        }

        const hasSelectedStories = feature.userStories.some((story) =>
          selectedUserStoryIdSet.has(story.id),
        );

        return selectedFeatureIdSet.has(feature.id) || hasSelectedStories;
      });

      const mappedFeatures = filteredFeatures.map((feature, featureIndex) => {
        const filteredStories = shouldFilterByDescendants
          ? feature.userStories.filter((story) => selectedUserStoryIdSet.has(story.id))
          : feature.userStories;

        const mappedUserStories = filteredStories.map((story) => ({
          id: story.id,
          title: story.description ?? '',
          description: story.name,
        }));

        return {
          id: `${epic.id}-F${String(featureIndex + 1).padStart(2, '0')}`,
          title: feature.name,
          description: feature.description || `Feature under epic ${epic.name}.`,
          userStories: mappedUserStories,
        };
      });

      epics.push({
        id: epic.id,
        title: epic.name,
        description: epic.description || `Epic ${epic.name}.`,
        features: mappedFeatures,
      });

      for (const feature of filteredFeatures) {
        const filteredStories = shouldFilterByDescendants
          ? feature.userStories.filter((story) => selectedUserStoryIdSet.has(story.id))
          : feature.userStories;

        systemFeatures.push({
          name: feature.name,
          description: feature.description || `Feature under epic ${epic.name}.`,
          userStories: filteredStories.map((story) => ({
            id: story.id,
            title: story.description ?? '',
            description: story.name,
          })),
        });

        for (const story of filteredStories) {
          functionalRequirements.push({
            id: `FR-${String(requirementIndex).padStart(3, '0')}`,
            title: story.description || 'No description provided.',
            description: story.name,
            priority: this.storyPriorityToFsdPriority(story.priority),
            relatedUserStory: story.id,
          });
          requirementIndex += 1;
        }
      }
    }

    const [screenshots, referenceDocumentsRaw, navigation, modules, rules, acceptance] =
      await Promise.all([
        this.prisma.fsdDashboardScreenshot.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdReferenceDocument.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdNavigationItem.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdFunctionalModule.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdBusinessRule.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
        this.prisma.fsdAcceptanceCriteria.findMany({
          where: { projectId },
          orderBy: [{ order: 'asc' }, { id: 'asc' }],
        }),
      ]);

    const dashboardScreenshots = screenshots.map((item) => ({
      url: item.url || '',
      altText: item.altText || 'Dashboard preview',
      caption: item.caption || 'Aperçu du tableau de bord',
    }));

    const referenceDocuments = referenceDocumentsRaw.map((item) => ({
      name: item.name || '',
      type: item.type || '',
      attachment: item.attachment || '',
    }));

    const navigationItems = navigation.map((item) => ({
      label: item.label || '',
      targetPage: item.targetPage || '',
      type: item.type || '',
      accessRoles: item.accessRoles || '',
    }));

    const approvals = project.approvals.map((approval) => ({
      name: approval.approverName || '',
      role: approval.approverRole || '',
      date: approval.approvalDate.toISOString(),
    }));

    const glossary = project.fsdGlossaryEntries.map((entry) => ({
      term: entry.term || '',
      comment: entry.comment || '',
    }));

    const revisions = project.fsdRevisions.map((revision) => ({
      date: revision.date.toISOString(),
      version: revision.version || '',
      status: revision.status || '',
      author: revision.author || '',
    }));

    const functionalModules = modules.map((module) => ({
      title: module.title || '',
      description: module.description || '',
    }));

    const businessRules = rules.map((rule, index) => ({
      id: rule.ruleId || `BR-${index + 1}`,
      title: rule.title || `Règle ${index + 1}`,
      description: rule.description || '',
      source: rule.source || undefined,
      priority: rule.priority || undefined,
    }));

    const acceptanceCriteria = acceptance.map((criterion, index) => ({
      id: criterion.criteriaId || `AC-${index + 1}`,
      userStory: criterion.userStory || '',
      given: criterion.given || '',
      when: criterion.when || '',
      then: criterion.then || '',
      status: this.normalizeAcceptanceStatus(criterion.status),
    }));

    const acceptanceCriteriaByUserStory = new Map<string, string[]>();
    for (const criterion of acceptanceCriteria) {
      const key = criterion.userStory?.trim();
      if (!key) {
        continue;
      }

      const item = `Étant donné ${criterion.given}. Quand ${criterion.when}. Alors ${criterion.then}.`;
      const list = acceptanceCriteriaByUserStory.get(key) || [];
      list.push(item);
      acceptanceCriteriaByUserStory.set(key, list);
    }

    const mappedEpicsWithAcceptance = epics.map((epic) => ({
      ...epic,
      features: epic.features.map((feature) => ({
        ...feature,
        userStories: feature.userStories.map((story) => ({
          ...story,
          acceptanceCriteria:
            acceptanceCriteriaByUserStory.get(story.id) ||
            acceptanceCriteriaByUserStory.get(story.title) ||
            [],
        })),
      })),
    }));

    const functionalDescription = project.description || '';

    const model: FsdDocumentModel = {
      metadata: {
        title: `Functional Specification Document - ${project.name}`,
        projectName: project.name,
        clientName: project.name,
        version: '1.0',
        date: new Date().toISOString(),
        author: 'System',
      },
      editValues: {},
      introduction: {
        purpose:
          project.description ||
          `Define functional scope and expected outcomes for ${project.name}.`,
        scope: `Epics, features, and user stories for ${project.name}.`,
        definitions: [],
      },
      overallDescription: {
        productPerspective:
          project.description ||
          `TestLab project ${project.name} functional scope.`,
        userClasses:
          'Business analysts, QA engineers, and product stakeholders.',
        assumptions:
          'Project data in TestLab is complete and maintained by delivery teams.',
      },
      projectOverview: project.description || '',
      methodology: '',
      glossary,
      revisions,
      functionalRequirements,
      nonFunctionalRequirements: {
        performance:
          'Document generation should complete in acceptable time for medium-sized projects.',
        security:
          'Only authorized users should access generated project documents.',
        usability:
          'Generated documents should be readable and consistent across export formats.',
      },
      systemFeatures,
      epics: mappedEpicsWithAcceptance,
      externalInterfaces: {
        userInterface: 'TestLab back-office web application.',
        apiInterfaces: 'NestJS REST endpoints and PostgreSQL data source.',
      },
      approvals,
      referenceDocuments,
      dashboardScreenshots,
      navigationItems,
      functionalDescription,
      functionalModules,
      businessRules,
      acceptanceCriteria,
      template: this.defaultTemplate,
    };

    if (options?.overrides?.metadata) {
      model.metadata = {
        ...model.metadata,
        ...this.omitUndefined(options.overrides.metadata),
      };
    }

    if (options?.overrides?.introduction) {
      model.introduction = {
        ...model.introduction,
        ...this.omitUndefined(options.overrides.introduction),
      };
    }

    if (options?.overrides?.overallDescription) {
      model.overallDescription = {
        ...model.overallDescription,
        ...this.omitUndefined(options.overrides.overallDescription),
      };
    }

    if (options?.overrides?.projectOverview !== undefined) {
      model.projectOverview = options.overrides.projectOverview;
    }

    if (options?.overrides?.methodology !== undefined) {
      model.methodology = options.overrides.methodology;
    }

    if (options?.overrides?.glossary !== undefined) {
      model.glossary = options.overrides.glossary;
    }

    if (options?.overrides?.revisions !== undefined) {
      model.revisions = options.overrides.revisions;
    }

    if (options?.overrides?.editValues !== undefined) {
      model.editValues = options.overrides.editValues;
    }

    if (model.introduction.definitions) {
      model.introduction.definitions = model.introduction.definitions.filter(
        (item) => item.term.trim() || item.definition.trim(),
      );
    }

    if (model.glossary) {
      model.glossary = model.glossary.filter(
        (item) => item.term.trim() || item.comment.trim(),
      );
    }

    if (model.revisions) {
      model.revisions = model.revisions.filter(
        (item) =>
          item.date.trim() ||
          item.version.trim() ||
          item.status.trim() ||
          item.author.trim(),
      );
    }

    return model;
  }

  private normalizeAcceptanceStatus(value: unknown): 'pass' | 'fail' | 'open' {
    const normalized = String(value || '')
      .toLowerCase()
      .trim();
    if (normalized === 'pass' || normalized === 'fail' || normalized === 'open') {
      return normalized;
    }

    return 'open';
  }

  private storyPriorityToFsdPriority(value: string): 'Critical' | 'High' | 'Medium' | 'Low' {
    const normalized = String(value || '').toUpperCase();

    if (normalized === 'HIGH') {
      return 'High';
    }

    if (normalized === 'LOW') {
      return 'Low';
    }

    return 'Medium';
  }

  private projectNumericId(projectId: string): number {
    const digits = projectId.replace(/\D/g, '');
    if (digits.length) {
      const parsed = Number.parseInt(digits.slice(0, 9), 10);
      if (Number.isInteger(parsed) && parsed > 0) {
        return parsed;
      }
    }

    let hash = 0;
    for (const char of projectId) {
      hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
    }

    return hash || 1;
  }

  private resolveAuthor(): string {
    return process.env.DOCUMENT_AUTHOR || process.env.USERNAME || 'System';
  }

  private omitUndefined<T extends Record<string, unknown>>(value: T): Partial<T> {
    const entries = Object.entries(value).filter(([, item]) => item !== undefined);
    return Object.fromEntries(entries) as Partial<T>;
  }

  private filterSelectedSuites(
    suites: CahierDocumentModel['suites'],
    selectedSuiteIds: Set<string>,
  ): CahierDocumentModel['suites'] {
    return suites
      .map((suite) => {
        const children = this.filterSelectedSuites(suite.children, selectedSuiteIds);
        const isSelected = selectedSuiteIds.has(suite.id);

        if (!isSelected && children.length === 0 && suite.testCases.length === 0) {
          return null;
        }

        return {
          ...suite,
          children,
        };
      })
      .filter((suite): suite is CahierDocumentModel['suites'][number] => suite !== null);
  }

  private filterSuitesBySelectedTestCases(
    suites: CahierDocumentModel['suites'],
    selectedTestCaseIds: Set<string>,
  ): CahierDocumentModel['suites'] {
    return suites
      .map((suite) => {
        const children = this.filterSuitesBySelectedTestCases(
          suite.children,
          selectedTestCaseIds,
        );
        const testCases = suite.testCases.filter((testCase) =>
          selectedTestCaseIds.has(testCase.id),
        );

        if (children.length === 0 && testCases.length === 0) {
          return null;
        }

        return {
          ...suite,
          children,
          testCases,
        };
      })
      .filter((suite): suite is CahierDocumentModel['suites'][number] => suite !== null);
  }

  private async ensureProjectExists(projectId: string): Promise<void> {
    const project = await this.prisma.project.findUnique({
      where: { id: projectId },
      select: { id: true },
    });

    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }
  }
}
